"""Initial schema: users, resumes, interview_sessions, recordings

Revision ID: fb15e9deacff
Revises: d6cc5906827a
Create Date: 2025-11-20 08:37:48.907365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb15e9deacff'
down_revision: Union[str, None] = 'd6cc5906827a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
